let quote = document.querySelector('.quoted');
let author = document.querySelector('.author');
const getquote = document.getElementById('quote_btn');
getquote.addEventListener('click', getrandomquote);


function getrandomquote() {
    var textArray = [
        "Aktivitas Kependudukan Berjarak Nasional",
        "Langkah Nasional Wajib Prokes Skala Besar",
        "Skema Nasional Interaksi Terbatas Menyeluruh Terstruktur",
        "Himbauan Nasional Warga Wajib Masker",
        "Aktivitas Kependudukan Resktriktif Tingkat Mikro",
        "Gerakan Nasional Pembatasan Aktivitas Masyarakat",
        "Kegiatan Kependudukan Berjarak Menyeluruh",
        "Pelaksanaan Restriksi Interaksi Masyarakat",
        "Masyarakat Wajib Masker Skala Nasional",
        "Pelaksanaan Pengurangan Interaksi Sosial",
        "Strategi Interaksi Berjarak Menyeluruh",
        "Strategi Nasional Interaksi Berjarak",
        "Restriksi Interaksi Menyeluruh",
        "Penerapan Pembatasan Interaksi Warga",
        "Gerakan Aktivitas Publik Berjarak",
        "Kegiatan Masyarakat Resktriktif Skala Masif",
        "Penerapan Jaga Jarak Zona Nasional",
        "Interaksi Resktriktif Tingkat Regional",
        "Interaksi Komunitas Resktriktif Nasional",
        "Himbauan Aktivitas Resktriktif",
        "Perealisasian Interaksi Publik Berjarak",
        "Penerapan Kegiatan Berjarak Nasional",
        "Perealisasian Kegiatan Kependudukan Berjarak",
        "Himbauan Kegiatan Resktriktif Berskala Regional",
        "Penutupan Aktivitas Nasional Gelombang 4",
        "Himbauan Nasional Kegiatan Resktriktif Menyeluruh Terstruktur",
        "Penutupan Kegiatan Bangsa Nasional Gelombang 2",
        "Pengetatan Kegiatan Warga Berskala Makro Terpadu",
        "Operasi Aktivitas Berjarak Nasional 4.0",
        "Himbauan Masyarakat Patuh Masker",
        "Bangsa Taat Masker Zona Makro Gelombang Lanjutan",
        "Interaksi Kependudukan Berjarak Skala Mikro",
        "Perealisasian Indonesia Taat Masker",
        "Gerakan Penjarakan Kegiatan Antarmuka 4.0",
        "Skema Supresi Kegiatan Warga",
        "Penutupan Kegiatan Tingkat Regional Sistematis",
        "Himbauan Indonesia Wajib Prokes",
        "Skema Nasional Restriksi Kegiatan Antarmuka",
        "Aktivitas Negara Resktriktif Skala Global",
        "Strategi Interaksi Resktriktif Tingkat Global 5.0",
        "Gerakan Nasional Aktivitas Berjarak Tingkat Makro Terpadu",
        "Pengaplikasian Taat Masker Zona Makro",
        "Pemberlakuan Penutupan Interaksi Penduduk 3.0",
        "Aktivitas Warga Berjarak Berskala Masif",
        "Skema Nasional Pengurangan Aktivitas Bangsa",
        "Kegiatan Publik Resktriktif Zona Mikro",
        "Operasi Interaksi Resktriktif Skala Makro",
        "Aktivitas Terbatas Tingkat Nasional",
        "Indonesia Taat Prokes Tingkat Nasional 2.0",
        "Penjarakan Aktivitas Zona Mikro Gelombang 4",
        "Pengurangan Kegiatan Berskala Regional",
        "Penutupan Kegiatan Zona Global",
        "Gerakan Kegiatan Terbatas",
        "Skema Warga Taat Jaga Jarak",
        "Gerakan Nasional Kegiatan Bangsa Terbatas",
        "Pengurangan Kegiatan Kependudukan Berskala Global",
        "Penutupan Kegiatan Kependudukan Berskala Besar",
        "Himbauan Restriksi Kegiatan Komunitas",
        "Supresi Aktivitas Penduduk Tingkat Makro",
        "Gerakan Nasional Pengetatan Aktivitas Penduduk",
        "Masyarakat Taat Jaga Jarak Zona Makro",
        "Gerakan Interaksi Masyarakat Resktriktif",
        "Pembatasan Interaksi Antarmuka Skala Besar",
        "Pemberlakuan Aktivitas Terbatas Skala Besar",
        "Himbauan Warga Patuh Jaga Jarak",
        "Langkah Nasional Interaksi Resktriktif Skala Besar Gelombang 2",
        "Pelaksanaan Jaga Jarak Tingkat Makro",
        "Operasi Indonesia Patuh Prokes Gelombang Lanjutan",
        "Himbauan Nasional Interaksi Warga Terbatas Terstruktur",
        "Langkah Nasional Kegiatan Bangsa Berjarak Terstruktur",
        "Supresi Kegiatan Menyeluruh",
        "Strategi Nasional Kegiatan Berjarak Menyeluruh",
        "Bangsa Patuh Jaga Jarak Nasional Terpadu",
        "Gerakan Patuh Jaga Jarak Zona Nasional",
        "Langkah Nasional Indonesia Patuh Masker",
        "Penutupan Kegiatan Penduduk Nasional",
        "Langkah Nasional Kegiatan Publik Resktriktif",
        "Kegiatan Bangsa Resktriktif Berskala Masif",
        "Gerakan Interaksi Berjarak Menyeluruh",
        "Skema Nasional Wajib Masker Berskala Mikro",
        "Supresi Kegiatan Publik Nasional Gelombang 3",
        "Himbauan Aktivitas Resktriktif Zona Nasional",
        "Pemberlakuan Patuh Prokes Skala Regional",
        "Gerakan Aktivitas Terbatas",
        "Pengaplikasian Bangsa Wajib Masker",
        "Skema Aktivitas Berjarak Zona Mikro",
        "Himbauan Nasional Kegiatan Terbatas",
        "Strategi Nasional Indonesia Taat Masker",
        "Indonesia Taat Jaga Jarak Nasional",
        "Operasi Warga Patuh Prokes",
        "Gerakan Kegiatan Masyarakat Berjarak 5.0",
        "Pengurangan Kegiatan Warga Menyeluruh",
        "Himbauan Nasional Interaksi Berjarak",
        "Penerapan Taat Prokes Menyeluruh",
        "Pemberlakuan Patuh Prokes Zona Nasional",
        "Kegiatan Resktriktif Zona Nasional",
        "Restriksi Interaksi Penduduk Nasional",
        "Masyarakat Wajib Prokes Tingkat Regional",
        "Aktivitas Sosial Resktriktif Berskala Makro",
        "Kegiatan Publik Terbatas Menyeluruh",
        "Aktivitas Terbatas Berskala Regional 5.0",
        "Pembatasan Kegiatan Skala Mikro",
        "Pelaksanaan Penutupan Aktivitas Antarmuka",
        "Gerakan Interaksi Berjarak",
        "Interaksi Berjarak Tingkat Makro Sistematis",
        "Penerapan Taat Jaga Jarak Nasional",
        "Aktivitas Publik Berjarak Berskala Mikro",
        "Skema Nasional Patuh Jaga Jarak Berskala Nasional Sistematis",
        "Skema Nasional Jaga Jarak Skala Global",
        "Pelaksanaan Aktivitas Komunitas Berjarak",
        "Strategi Nasional Taat Jaga Jarak Menyeluruh Terpadu",
        "Pelaksanaan Taat Jaga Jarak Skala Mikro",
        "Aktivitas Kependudukan Resktriktif Nasional",
        "Pemberlakuan Aktivitas Resktriktif Menyeluruh",
        "Gerakan Nasional Wajib Masker Zona Makro",
        "Penutupan Aktivitas Antarmuka Zona Regional",
        "Himbauan Nasional Kegiatan Resktriktif Menyeluruh",
        "Supresi Aktivitas Berskala Mikro",
        "Himbauan Nasional Wajib Masker Menyeluruh",
        "Penerapan Kegiatan Publik Terbatas",
        "Langkah Nasional Taat Prokes Zona Regional",
        "Gerakan Pengetatan Aktivitas Bangsa Terstruktur",
        "Aktivitas Terbatas Berskala Makro",
        "Aktivitas Resktriktif Menyeluruh Sistematis",
        "Kegiatan Publik Terbatas Zona Global",
        "Aktivitas Sosial Terbatas Menyeluruh",
        "Kegiatan Resktriktif Skala Besar",
        "Warga Taat Jaga Jarak Skala Masif",
        "Interaksi Berjarak Nasional",
        "Strategi Kegiatan Komunitas Resktriktif",
        "Langkah Nasional Taat Masker Nasional",
        "Penutupan Kegiatan Negara Menyeluruh",
        "Strategi Nasional Aktivitas Kependudukan Berjarak",
        "Langkah Nasional Aktivitas Kependudukan Terbatas Sistematis",
        "Pengetatan Aktivitas Nasional",
        "Penerapan Penjarakan Kegiatan Antarmuka",
        "Skema Nasional Aktivitas Berjarak Skala Nasional Terstruktur",
        "Bangsa Taat Jaga Jarak Berskala Besar Sistematis",
        "Masyarakat Wajib Prokes Tingkat Makro",
        "Skema Kegiatan Kependudukan Resktriktif",
        "Himbauan Nasional Kegiatan Warga Terbatas",
        "Pengetatan Aktivitas Warga Nasional",
        "Restriksi Aktivitas Publik Nasional",
        "Strategi Nasional Aktivitas Masyarakat Terbatas",
        "Aktivitas Negara Resktriktif Zona Global Terstruktur",
        "Skema Bangsa Wajib Prokes",
        "Gerakan Penjarakan Interaksi Penduduk",
        "Pengaplikasian Aktivitas Kependudukan Berjarak 3.0",
        "Kegiatan Berjarak Berskala Besar",
        "Strategi Nasional Kegiatan Terbatas Berskala Makro",
        "Interaksi Publik Berjarak Nasional",
        "Kegiatan Terbatas Zona Mikro",
        "Skema Patuh Jaga Jarak Skala Mikro",
        "Warga Taat Jaga Jarak Nasional",
        "Skema Nasional Aktivitas Terbatas Periode 2",
        "Supresi Kegiatan Berskala Masif",
        "Aktivitas Komunitas Terbatas Skala Mikro",
        "Langkah Nasional Aktivitas Terbatas Berskala Mikro",
        "Interaksi Antarmuka Resktriktif Nasional",
        "Pengurangan Interaksi Kependudukan Tingkat Global",
        "Penerapan Pembatasan Aktivitas Komunitas",
        "Operasi Aktivitas Berjarak",
        "Bangsa Patuh Prokes Berskala Regional",
        "Bangsa Wajib Prokes Tingkat Global",
        "Interaksi Resktriktif Zona Regional Terpadu",
        "Interaksi Masyarakat Berjarak Tingkat Makro Gelombang 5",
        "Pemberlakuan Kegiatan Terbatas Terstruktur",
        "Gerakan Nasional Interaksi Resktriktif Skala Mikro Terpadu",
        "Himbauan Pengetatan Aktivitas Warga",
        "Pemberlakuan Warga Taat Prokes",
        "Perealisasian Aktivitas Terbatas Skala Global 2.0",
        "Langkah Nasional Taat Masker Skala Makro Sistematis",
        "Langkah Nasional Pembatasan Kegiatan Sosial",
        "Interaksi Resktriktif Berskala Regional Sistematis",
        "Interaksi Terbatas Skala Regional",
        "Penjarakan Kegiatan Antarmuka Nasional Terpadu",
        "Gerakan Nasional Kegiatan Publik Terbatas 3.0",
        "Operasi Kegiatan Resktriktif",
        "Pengetatan Interaksi Bangsa Tingkat Makro",
        "Penerapan Interaksi Penduduk Terbatas",
        "Himbauan Nasional Warga Patuh Masker",
        "Penerapan Kegiatan Negara Terbatas Terstruktur",
        "Penutupan Interaksi Zona Mikro",
        "Perealisasian Bangsa Wajib Jaga Jarak",
        "Aktivitas Berjarak Skala Nasional",
        "Aktivitas Resktriktif Nasional Sistematis",
        "Gerakan Nasional Jaga Jarak Berskala Besar",
        "Himbauan Penjarakan Interaksi Penduduk",
        "Kegiatan Kependudukan Berjarak Zona Regional",
        "Gerakan Patuh Jaga Jarak Zona Global",
        "Langkah Nasional Supresi Aktivitas Sosial",
        "Supresi Kegiatan Masyarakat Berskala Nasional",
        "Restriksi Interaksi Negara Menyeluruh",
        "Pembatasan Kegiatan Skala Besar",
        "Masyarakat Taat Masker Nasional",
        "Indonesia Wajib Masker Nasional",
        "Pengaplikasian Kegiatan Warga Berjarak",
        "Langkah Nasional Kegiatan Berjarak",
        "Strategi Masyarakat Patuh Masker",
        "Himbauan Masyarakat Wajib Jaga Jarak",
        "Langkah Nasional Patuh Prokes Berskala Besar",
        "Strategi Nasional Interaksi Resktriktif Berskala Besar",
        "Interaksi Warga Resktriktif Nasional",
        "Langkah Nasional Patuh Jaga Jarak Zona Regional Terstruktur",
        "Pengaplikasian Kegiatan Terbatas",
        "Aktivitas Berjarak Zona Regional",
        "Himbauan Nasional Wajib Masker Berskala Regional Sistematis",
        "Aktivitas Resktriktif Menyeluruh",
        "Aktivitas Resktriktif Zona Makro",
        "Gerakan Nasional Wajib Masker Berskala Besar",
        "Perealisasian Penjarakan Aktivitas Komunitas",
        "Kegiatan Terbatas Skala Regional",
        "Interaksi Terbatas Berskala Global",
        "Supresi Interaksi Tingkat Global Periode Lanjutan",
        "Interaksi Bangsa Berjarak Skala Mikro",
        "Operasi Taat Prokes Menyeluruh",
        "Langkah Nasional Patuh Prokes Skala Mikro",
        "Pelaksanaan Interaksi Berjarak Zona Mikro",
        "Operasi Interaksi Terbatas",
        "Aktivitas Berjarak Menyeluruh",
        "Pengaplikasian Taat Jaga Jarak Berskala Masif Terpadu",
        "Kegiatan Antarmuka Berjarak Skala Global",
        "Kegiatan Sosial Terbatas Tingkat Mikro",
        "Strategi Nasional Kegiatan Penduduk Resktriktif",
        "Kegiatan Resktriktif Nasional",
        "Langkah Nasional Warga Wajib Prokes Sistematis",
        "Himbauan Nasional Kegiatan Publik Resktriktif",
        "Himbauan Nasional Patuh Prokes Berskala Masif",
        "Restriksi Interaksi Sosial Nasional 5.0",
        "Gerakan Nasional Interaksi Komunitas Berjarak",
        "Warga Wajib Jaga Jarak Menyeluruh",
        "Strategi Nasional Restriksi Kegiatan Komunitas",
        "Kegiatan Warga Resktriktif Nasional",
        "Strategi Nasional Taat Masker Berskala Global",
        "Masyarakat Wajib Prokes Menyeluruh",
        "Strategi Nasional Taat Jaga Jarak Berskala Nasional",
        "Perealisasian Wajib Prokes Menyeluruh Periode Lanjutan",
        "Pengetatan Interaksi Menyeluruh Sistematis",
        "Aktivitas Masyarakat Resktriktif Zona Global Gelombang 5",
        "Restriksi Interaksi Masyarakat Nasional",
        "Pengetatan Kegiatan Bangsa Menyeluruh Terstruktur",
        "Restriksi Interaksi Skala Makro",
        "Indonesia Taat Masker Tingkat Regional",
        "Penerapan Interaksi Antarmuka Berjarak Sistematis",
        "Penutupan Aktivitas Antarmuka Skala Makro",
        "Skema Interaksi Terbatas Nasional",
        "Restriksi Aktivitas Publik Skala Makro Sistematis",
        "Interaksi Antarmuka Resktriktif Skala Nasional",
        "Gerakan Nasional Aktivitas Terbatas",
        "Himbauan Interaksi Resktriktif Menyeluruh",
        "Langkah Nasional Wajib Jaga Jarak Menyeluruh",
        "Operasi Patuh Jaga Jarak Menyeluruh Terstruktur",
        "Gerakan Nasional Kegiatan Komunitas Terbatas",
        "Masyarakat Taat Prokes Berskala Global",
        "Pengaplikasian Taat Jaga Jarak Tingkat Makro",
        "Indonesia Taat Prokes Berskala Mikro",
        "Warga Patuh Masker Nasional",
        "Indonesia Taat Jaga Jarak Berskala Global",
        "Perealisasian Masyarakat Patuh Jaga Jarak",
        "Bangsa Taat Jaga Jarak Skala Nasional 2.0",
        "Penerapan Kegiatan Terbatas Sistematis",
        "Indonesia Wajib Masker Zona Global",
        "Supresi Interaksi Berskala Regional",
        "Warga Wajib Prokes Menyeluruh",
        "Skema Nasional Indonesia Taat Masker Sistematis",
        "Himbauan Bangsa Taat Masker Terstruktur",
        "Kegiatan Masyarakat Terbatas Nasional",
        "Gerakan Kegiatan Resktriktif Nasional",
        "Himbauan Nasional Penjarakan Interaksi Penduduk",
        "Supresi Kegiatan Nasional Terstruktur",
        "Strategi Nasional Interaksi Berjarak Tingkat Regional",
        "Skema Nasional Aktivitas Sosial Resktriktif",
        "Indonesia Patuh Jaga Jarak Nasional Terstruktur",
        "Restriksi Aktivitas Masyarakat Menyeluruh",
        "Interaksi Negara Terbatas Nasional",
        "Himbauan Nasional Masyarakat Taat Jaga Jarak",
        "Strategi Nasional Restriksi Aktivitas Masyarakat Terstruktur",
        "Operasi Aktivitas Publik Berjarak",
        "Strategi Kegiatan Penduduk Berjarak",
        "Pelaksanaan Pembatasan Interaksi Publik",
        "Strategi Penjarakan Interaksi Kependudukan Terstruktur",
        "Skema Nasional Interaksi Masyarakat Terbatas",
        "Kegiatan Bangsa Terbatas Zona Global",
        "Gerakan Nasional Bangsa Jaga Jarak",
        "Pelaksanaan Patuh Prokes Nasional",
        "Skema Nasional Aktivitas Masyarakat Terbatas Terstruktur",
        "Penerapan Kegiatan Terbatas Tingkat Makro",
        "Strategi Nasional Interaksi Terbatas Nasional",
        "Pelaksanaan Aktivitas Warga Berjarak",
        "Aktivitas Antarmuka Berjarak Menyeluruh Sistematis",
        "Skema Nasional Kegiatan Komunitas Resktriktif",
        "Perealisasian Wajib Masker Tingkat Nasional",
        "Bangsa Taat Jaga Jarak Zona Global",
        "Skema Interaksi Terbatas",
        "Pengaplikasian Interaksi Terbatas Skala Besar",
        "Langkah Nasional Restriksi Kegiatan Sosial Terpadu",
        "Pengurangan Kegiatan Publik Skala Global",
        "Operasi Supresi Interaksi Sosial 2.0",
        "Perealisasian Warga Patuh Masker",
        "Perealisasian Aktivitas Terbatas Zona Regional",
        "Interaksi Berjarak Tingkat Nasional",
        "Pelaksanaan Interaksi Berjarak Menyeluruh Periode 4",
        "Warga Patuh Masker Menyeluruh",
        "Gerakan Pengurangan Interaksi Negara",
        "Gerakan Nasional Aktivitas Berjarak",
        "Pembatasan Aktivitas Zona Regional",
        "Skema Aktivitas Negara Terbatas",
        "Penerapan Aktivitas Bangsa Terbatas",
        "Kegiatan Antarmuka Resktriktif Tingkat Regional",
        "Gerakan Nasional Interaksi Publik Resktriktif",
        "Strategi Nasional Masyarakat Taat Prokes",
        "Perealisasian Kegiatan Berjarak",
        "Pengetatan Aktivitas Zona Regional",
        "Himbauan Nasional Patuh Masker Nasional Gelombang 3",
        "Pelaksanaan Wajib Masker Zona Mikro",
        "Pembatasan Aktivitas Zona Mikro",
        "Skema Kegiatan Resktriktif",
        "Perealisasian Taat Jaga Jarak Berskala Masif",
        "Gerakan Nasional Pengetatan Interaksi Negara Terpadu",
        "Pemberlakuan Kegiatan Terbatas Tingkat Mikro",
        "Gerakan Kegiatan Berjarak",
        "Bangsa Taat Masker Tingkat Nasional",
        "Langkah Nasional Warga Taat Jaga Jarak",
        "Strategi Nasional Aktivitas Warga Resktriktif",
        "Indonesia Taat Prokes Tingkat Nasional",
        "Warga Taat Prokes Berskala Masif",
        "Pengetatan Interaksi Skala Besar",
        "Aktivitas Berjarak Zona Mikro Gelombang Lanjutan",
        "Pengaplikasian Interaksi Resktriktif Skala Masif",
        "Pemberlakuan Interaksi Warga Terbatas",
        "Gerakan Indonesia Taat Masker",
        "Skema Nasional Kegiatan Penduduk Terbatas",
        "Supresi Interaksi Tingkat Makro Terpadu",
        "Warga Patuh Masker Skala Regional 3.0",
        "Langkah Nasional Aktivitas Bangsa Terbatas",
        "Bangsa Patuh Jaga Jarak Skala Mikro",
        "Interaksi Masyarakat Terbatas Tingkat Nasional",
        "Skema Wajib Masker Berskala Mikro",
        "Masyarakat Jaga Jarak Skala Makro",
        "Himbauan Nasional Aktivitas Kependudukan Resktriktif",
        "Pelaksanaan Kegiatan Resktriktif",
        "Kegiatan Masyarakat Resktriktif Skala Mikro",
        "Perealisasian Warga Wajib Prokes Terpadu",
        "Gerakan Nasional Warga Wajib Jaga Jarak",
        "Himbauan Interaksi Terbatas Periode 3",
        "Gerakan Taat Prokes Menyeluruh",
        "Gerakan Nasional Bangsa Taat Jaga Jarak 2.0",
        "Himbauan Patuh Masker Skala Besar Terpadu",
        "Aktivitas Terbatas Zona Global",
        "Bangsa Taat Masker Tingkat Global",
        "Kegiatan Komunitas Berjarak Berskala Mikro",
        "Pengetatan Kegiatan Skala Mikro",
        "Penutupan Aktivitas Berskala Nasional",
        "Skema Interaksi Bangsa Berjarak",
        "Perealisasian Aktivitas Masyarakat Terbatas",
        "Pengetatan Interaksi Zona Global",
        "Warga Patuh Prokes Nasional",
        "Skema Wajib Jaga Jarak Berskala Regional",
        "Strategi Wajib Masker Tingkat Mikro",
        "Penutupan Aktivitas Bangsa Berskala Global",
        "Penerapan Interaksi Berjarak Tingkat Regional",
        "Gerakan Nasional Masyarakat Patuh Jaga Jarak",
        "Pembatasan Kegiatan Zona Global",
        "Langkah Nasional Pengurangan Aktivitas Publik",
        "Himbauan Nasional Patuh Prokes Zona Global",
        "Penerapan Kegiatan Berjarak",
        "Bangsa Wajib Masker Tingkat Mikro",
        "Pelaksanaan Supresi Aktivitas Penduduk",
        "Gerakan Kegiatan Berjarak Zona Global",
        "Himbauan Nasional Aktivitas Resktriktif Skala Masif Terpadu",
        "Penjarakan Kegiatan Sosial Skala Masif",
        "Gerakan Taat Masker Zona Regional",
        "Bangsa Taat Jaga Jarak Menyeluruh",
        "Interaksi Warga Resktriktif Skala Nasional",
        "Strategi Nasional Aktivitas Negara Resktriktif",
        "Penjarakan Kegiatan Zona Makro",
        "Restriksi Interaksi Warga Zona Nasional",
        "Gerakan Nasional Kegiatan Resktriktif Sistematis",
        "Strategi Nasional Penutupan Aktivitas Bangsa 4.0",
        "Kegiatan Antarmuka Resktriktif Nasional",
        "Pemberlakuan Taat Prokes Skala Regional Terpadu",
        "Masyarakat Wajib Prokes Zona Makro",
        "Strategi Aktivitas Resktriktif Terpadu",
        "Skema Aktivitas Masyarakat Berjarak 3.0",
        "Interaksi Berjarak Berskala Makro",
        "Strategi Taat Masker Berskala Besar",
        "Penerapan Wajib Masker Berskala Mikro",
        "Penjarakan Aktivitas Zona Nasional",
        "Skema Nasional Taat Masker Skala Regional",
        "Perealisasian Wajib Prokes Tingkat Nasional 5.0",
        "Indonesia Patuh Jaga Jarak Menyeluruh",
        "Operasi Patuh Prokes Tingkat Regional",
        "Aktivitas Warga Berjarak Tingkat Mikro",
        "Himbauan Nasional Penutupan Kegiatan Kependudukan",
        "Indonesia Wajib Masker Skala Masif Terpadu",
        "Pemberlakuan Interaksi Penduduk Resktriktif",
        "Penerapan Interaksi Berjarak",
        "Gerakan Pengurangan Aktivitas Negara",
        "Himbauan Indonesia Wajib Jaga Jarak",
        "Masyarakat Jaga Jarak Skala Mikro",
        "Langkah Nasional Kegiatan Antarmuka Resktriktif",
        "Indonesia Patuh Prokes Tingkat Global",
        "Gerakan Nasional Kegiatan Berjarak",
        "Pengaplikasian Interaksi Bangsa Resktriktif",
        "Kegiatan Terbatas Berskala Makro",
        "Interaksi Antarmuka Resktriktif Tingkat Regional",
        "Pengurangan Interaksi Masyarakat Nasional",
        "Indonesia Patuh Jaga Jarak Skala Besar",
        "Masyarakat Taat Jaga Jarak Nasional Terpadu",
        "Masyarakat Wajib Prokes Skala Mikro",
        "Gerakan Nasional Bangsa Taat Jaga Jarak",
        "Supresi Aktivitas Nasional",
        "Pelaksanaan Aktivitas Terbatas",
        "Gerakan Nasional Patuh Jaga Jarak Skala Makro",
        "Indonesia Wajib Jaga Jarak Zona Regional",
        "Interaksi Resktriktif Skala Besar",
        "Pengurangan Kegiatan Warga Nasional",
        "Warga Wajib Prokes Zona Nasional",
        "Interaksi Publik Terbatas Zona Makro",
        "Masyarakat Patuh Masker Menyeluruh Sistematis",
        "Operasi Interaksi Berjarak",
        "Skema Kegiatan Resktriktif Menyeluruh",
        "Gerakan Nasional Kegiatan Terbatas",
        "Indonesia Jaga Jarak Berskala Global",
        "Himbauan Nasional Wajib Prokes Menyeluruh",
        "Pengurangan Interaksi Warga Menyeluruh Terpadu",
        "Penerapan Bangsa Patuh Jaga Jarak",
        "Operasi Interaksi Terbatas Tingkat Regional Terstruktur",
        "Interaksi Antarmuka Terbatas Skala Besar 5.0",
        "Masyarakat Patuh Prokes Skala Nasional",
        "Pengurangan Interaksi Publik Tingkat Nasional",
        "Pengurangan Aktivitas Kependudukan Tingkat Makro",
        "Operasi Wajib Prokes Menyeluruh",
        "Warga Taat Masker Zona Nasional",
        "Indonesia Jaga Jarak Skala Regional Terstruktur",
        "Himbauan Bangsa Patuh Jaga Jarak",
        "Pengurangan Aktivitas Masyarakat Nasional",
        "Aktivitas Negara Terbatas Menyeluruh",
        "Skema Aktivitas Berjarak Zona Regional",
        "Bangsa Wajib Masker Skala Besar",
        "Aktivitas Terbatas Menyeluruh",
        "Skema Interaksi Berjarak Nasional",
        "Pembatasan Interaksi Negara Zona Global",
        "Supresi Interaksi Komunitas Zona Mikro",
        "Himbauan Nasional Wajib Masker Zona Mikro",
        "Aktivitas Penduduk Berjarak Menyeluruh",
        "Pengetatan Aktivitas Tingkat Nasional",
        "Skema Pembatasan Aktivitas Kependudukan",
        "Pengurangan Aktivitas Tingkat Global",
        "Langkah Nasional Interaksi Masyarakat Terbatas Periode 5",
        "Restriksi Interaksi Bangsa Skala Makro",
        "Penutupan Kegiatan Tingkat Makro",
        "Pengaplikasian Interaksi Berjarak Gelombang 4",
        "Langkah Nasional Masyarakat Jaga Jarak Sistematis",
        "Strategi Nasional Interaksi Berjarak Berskala Makro",
        "Penerapan Pengurangan Kegiatan Publik",
        "Kegiatan Terbatas Skala Global",
        "Aktivitas Publik Berjarak Skala Masif",
        "Operasi Penutupan Kegiatan Publik",
        "Himbauan Pengurangan Aktivitas Kependudukan",
        "Strategi Interaksi Resktriktif Skala Besar",
        "Pengetatan Kegiatan Antarmuka Nasional Terstruktur",
        "Aktivitas Penduduk Resktriktif Zona Makro",
        "Skema Nasional Interaksi Resktriktif",
        "Aktivitas Kependudukan Resktriktif Berskala Makro",
        "Penerapan Aktivitas Berjarak Menyeluruh",
        "Pengaplikasian Kegiatan Kependudukan Terbatas",
        "Pembatasan Interaksi Warga Nasional",
        "Perealisasian Bangsa Jaga Jarak",
        "Penjarakan Interaksi Komunitas Zona Regional",
        "Aktivitas Berjarak Tingkat Regional Sistematis",
        "Penerapan Interaksi Penduduk Berjarak Terstruktur",
        "Supresi Aktivitas Sosial Nasional 4.0",
        "Interaksi Masyarakat Terbatas Tingkat Global",
        "Himbauan Nasional Kegiatan Berjarak",
        "Pembatasan Kegiatan Penduduk Berskala Masif",
        "Warga Jaga Jarak Berskala Global",
        "Kegiatan Resktriktif Zona Global",
        "Pemberlakuan Masyarakat Jaga Jarak",
        "Kegiatan Berjarak Tingkat Makro",
        "Aktivitas Publik Berjarak Skala Nasional",
        "Penerapan Aktivitas Berjarak Berskala Mikro",
        "Operasi Bangsa Wajib Masker",
        "Pemberlakuan Wajib Masker Menyeluruh Terpadu",
        "Operasi Kegiatan Berjarak 5.0",
        "Langkah Nasional Kegiatan Resktriktif Tingkat Regional 3.0",
        "Pelaksanaan Taat Masker Nasional",
        "Interaksi Sosial Terbatas Skala Global",
        "Pelaksanaan Wajib Prokes Skala Makro",
        "Interaksi Berjarak Berskala Besar",
        "Gerakan Nasional Bangsa Patuh Prokes",
        "Penutupan Kegiatan Skala Masif",
        "Pemberlakuan Masyarakat Patuh Prokes Periode 5",
        "Pemberlakuan Kegiatan Resktriktif Skala Global",
        "Pelaksanaan Indonesia Taat Prokes",
        "Penerapan Kegiatan Resktriktif Tingkat Mikro",
        "Warga Taat Prokes Nasional",
        "Perealisasian Warga Wajib Jaga Jarak",
        "Penerapan Aktivitas Resktriktif",
        "Penutupan Interaksi Publik Skala Masif Terstruktur",
        "Operasi Interaksi Berjarak Berskala Regional",
        "Kegiatan Terbatas Zona Nasional 4.0",
        "Penjarakan Kegiatan Tingkat Global",
        "Perealisasian Kegiatan Resktriktif Menyeluruh",
        "Skema Nasional Kegiatan Publik Resktriktif",
        "Indonesia Taat Masker Nasional",
        "Aktivitas Masyarakat Terbatas Nasional",
        "Pengetatan Interaksi Zona Regional Terstruktur",
        "Aktivitas Negara Berjarak Nasional",
        "Strategi Interaksi Terbatas",
        "Interaksi Bangsa Terbatas Nasional",
        "Interaksi Masyarakat Terbatas Berskala Nasional",
        "Gerakan Penjarakan Interaksi Negara Periode Lanjutan",
        "Pemberlakuan Indonesia Taat Prokes Terpadu",
        "Penjarakan Interaksi Antarmuka Skala Nasional",
        "Gerakan Pengurangan Kegiatan Bangsa",
        "Penjarakan Aktivitas Publik Nasional Gelombang 3",
        "Gerakan Penjarakan Kegiatan Negara",
        "Pemberlakuan Kegiatan Berjarak Menyeluruh",
        "Himbauan Nasional Kegiatan Terbatas Terstruktur",
        "Operasi Indonesia Taat Prokes",
        "Kegiatan Publik Berjarak Tingkat Mikro",
        "Operasi Penjarakan Aktivitas Bangsa",
        "Langkah Nasional Kegiatan Masyarakat Berjarak",
        "Gerakan Taat Prokes Zona Makro",
        "Perealisasian Indonesia Patuh Prokes",
        "Skema Nasional Warga Jaga Jarak",
        "Langkah Nasional Patuh Jaga Jarak Skala Makro",
        "Strategi Pengurangan Aktivitas Masyarakat",
        "Interaksi Warga Resktriktif Zona Makro",
        "Kegiatan Publik Berjarak Berskala Global",
        "Kegiatan Warga Resktriktif Skala Nasional",
        "Restriksi Interaksi Tingkat Makro 4.0",
        "Pelaksanaan Kegiatan Terbatas Terstruktur",
        "Bangsa Patuh Prokes Berskala Nasional 4.0",
        "Skema Nasional Interaksi Penduduk Berjarak Periode Lanjutan",
        "Himbauan Nasional Patuh Masker Menyeluruh",
        "Supresi Interaksi Berskala Besar",
        "Langkah Nasional Warga Patuh Masker",
        "Supresi Kegiatan Negara Skala Regional",
        "Pengetatan Kegiatan Publik Skala Besar Terstruktur",
        "Pelaksanaan Interaksi Resktriktif Tingkat Makro",
        "Pemberlakuan Wajib Prokes Tingkat Regional",
        "Supresi Kegiatan Warga Nasional",
        "Penutupan Kegiatan Warga Berskala Global Sistematis",
        "Interaksi Berjarak Skala Mikro Periode 3",
        "Pemberlakuan Aktivitas Berjarak Zona Nasional",
        "Langkah Nasional Aktivitas Terbatas Gelombang 2",
        "Pemberlakuan Kegiatan Resktriktif Zona Makro Terstruktur",
        "Pemberlakuan Penutupan Kegiatan Kependudukan",
        "Interaksi Terbatas Zona Global Terpadu",
        "Pelaksanaan Warga Patuh Jaga Jarak",
        "Pengurangan Aktivitas Penduduk Skala Masif Sistematis",
        "Pembatasan Kegiatan Antarmuka Tingkat Nasional Sistematis",
        "Pengetatan Interaksi Sosial Menyeluruh",
        "Pemberlakuan Supresi Aktivitas Komunitas",
        "Interaksi Bangsa Resktriktif Zona Mikro",
        "Interaksi Bangsa Terbatas Skala Regional",
        "Strategi Nasional Restriksi Interaksi Publik",
        "Aktivitas Sosial Resktriktif Tingkat Regional 5.0",
        "Pengetatan Interaksi Komunitas Skala Masif Terpadu",
        "Langkah Nasional Aktivitas Masyarakat Berjarak",
        "Perealisasian Bangsa Taat Prokes",
        "Himbauan Jaga Jarak Berskala Besar",
        "Langkah Nasional Aktivitas Negara Berjarak 4.0",
        "Penutupan Kegiatan Sosial Menyeluruh",
        "Supresi Aktivitas Skala Makro",
        "Penjarakan Kegiatan Tingkat Mikro",
        "Pengurangan Kegiatan Warga Zona Makro",
        "Langkah Nasional Penjarakan Interaksi Kependudukan",
        "Pengaplikasian Pembatasan Kegiatan Publik",
        "Perealisasian Interaksi Terbatas Skala Global",
        "Strategi Aktivitas Warga Resktriktif Sistematis",
        "Strategi Nasional Pengurangan Interaksi Bangsa",
        "Gerakan Kegiatan Resktriktif Zona Regional",
        "Pembatasan Kegiatan Tingkat Makro",
        "Kegiatan Bangsa Berjarak Nasional",
        "Interaksi Resktriktif Berskala Mikro",
        "Indonesia Patuh Jaga Jarak Tingkat Nasional Terstruktur",
        "Pengaplikasian Aktivitas Resktriktif Zona Regional Sistematis",
        "Strategi Nasional Kegiatan Berjarak 3.0",
        "Pengurangan Kegiatan Warga Skala Besar",
        "Operasi Penutupan Kegiatan Bangsa",
        "Penjarakan Aktivitas Bangsa Berskala Global",
        "Aktivitas Warga Resktriktif Tingkat Nasional Terpadu",
        "Operasi Wajib Prokes Berskala Makro",
        "Supresi Kegiatan Nasional",
        "Pengaplikasian Kegiatan Terbatas Zona Makro",
        "Restriksi Kegiatan Skala Global",
        "Gerakan Masyarakat Wajib Masker",
        "Pelaksanaan Aktivitas Berjarak Tingkat Regional",
        "Bangsa Jaga Jarak Nasional",
        "Pelaksanaan Bangsa Patuh Jaga Jarak Terstruktur",
        "Gerakan Nasional Interaksi Negara Resktriktif",
        "Pelaksanaan Kegiatan Berjarak",
        "Indonesia Wajib Prokes Berskala Makro Terstruktur",
        "Pemberlakuan Aktivitas Terbatas",
        "Pembatasan Interaksi Skala Regional",
        "Gerakan Nasional Aktivitas Berjarak Menyeluruh Sistematis",
        "Penutupan Interaksi Sosial Nasional",
        "Kegiatan Negara Resktriktif Tingkat Makro 5.0",
        "Penerapan Masyarakat Taat Jaga Jarak",
        "Perealisasian Aktivitas Berjarak",
        "Himbauan Kegiatan Berjarak 2.0",
        "Operasi Wajib Masker Nasional",
        "Kegiatan Penduduk Berjarak Skala Global",
        "Interaksi Berjarak Berskala Mikro Sistematis",
        "Interaksi Publik Terbatas Zona Regional",
        "Masyarakat Patuh Prokes Menyeluruh",
        "Pengetatan Kegiatan Skala Besar",
        "Himbauan Nasional Penjarakan Kegiatan Kependudukan",
        "Strategi Nasional Warga Taat Prokes Gelombang 4",
        "Bangsa Patuh Jaga Jarak Skala Global",
        "Skema Nasional Supresi Kegiatan Sosial",
        "Gerakan Nasional Kegiatan Kependudukan Terbatas",
        "Supresi Kegiatan Berskala Mikro",
        "Masyarakat Jaga Jarak Zona Regional Sistematis",
        "Interaksi Resktriktif Tingkat Mikro Terstruktur",
        "Strategi Warga Taat Prokes",
        "Strategi Interaksi Negara Resktriktif",
        "Aktivitas Antarmuka Terbatas Menyeluruh",
        "Pengaplikasian Penjarakan Interaksi Bangsa",
        "Penutupan Interaksi Tingkat Global",
        "Strategi Nasional Bangsa Jaga Jarak",
        "Pembatasan Aktivitas Nasional Terstruktur",
        "Strategi Nasional Kegiatan Terbatas",
        "Skema Wajib Jaga Jarak Berskala Masif",
        "Pengaplikasian Aktivitas Terbatas Berskala Nasional",
        "Kegiatan Publik Resktriktif Zona Regional Periode 2",
        "Kegiatan Kependudukan Berjarak Skala Besar",
        "Skema Taat Jaga Jarak Menyeluruh",
        "Himbauan Kegiatan Bangsa Resktriktif",
        "Aktivitas Sosial Berjarak Tingkat Regional",
        "Aktivitas Masyarakat Berjarak Zona Mikro Sistematis",
        "Pengaplikasian Interaksi Berjarak",
        "Kegiatan Terbatas Tingkat Makro",
        "Aktivitas Warga Terbatas Zona Mikro",
        "Masyarakat Taat Jaga Jarak Skala Global",
        "Himbauan Nasional Pembatasan Kegiatan Masyarakat Gelombang 4",
        "Strategi Kegiatan Terbatas",
        "Gerakan Nasional Aktivitas Terbatas Gelombang 5",
        "Pengetatan Interaksi Skala Regional",
        "Skema Nasional Supresi Aktivitas Kependudukan",
        "Pengaplikasian Restriksi Kegiatan Komunitas",
        "Interaksi Komunitas Berjarak Skala Regional Sistematis",
        "Bangsa Taat Prokes Zona Mikro",
        "Warga Taat Jaga Jarak Menyeluruh",
        "Kegiatan Penduduk Berjarak Menyeluruh Terpadu",
        "Skema Supresi Kegiatan Negara",
        "Langkah Nasional Aktivitas Berjarak Menyeluruh",
        "Penerapan Penutupan Aktivitas Negara",
        "Indonesia Patuh Masker Berskala Besar",
        "Skema Kegiatan Warga Terbatas",
        "Pengaplikasian Interaksi Negara Terbatas Gelombang 3",
        "Gerakan Nasional Kegiatan Berjarak Tingkat Regional",
        "Indonesia Wajib Prokes Tingkat Global",
        "Interaksi Terbatas Menyeluruh",
        "Langkah Nasional Aktivitas Terbatas Berskala Makro",
        "Pengaplikasian Wajib Jaga Jarak Nasional",
        "Pengetatan Kegiatan Penduduk Berskala Regional",
        "Operasi Warga Patuh Jaga Jarak",
        "Restriksi Kegiatan Warga Zona Makro",
        "Langkah Nasional Kegiatan Komunitas Berjarak",
        "Gerakan Warga Patuh Prokes",
        "Restriksi Kegiatan Sosial Skala Nasional",
        "Pemberlakuan Aktivitas Resktriktif Berskala Regional",
        "Operasi Interaksi Negara Berjarak",
        "Strategi Taat Prokes Menyeluruh",
        "Gerakan Aktivitas Warga Berjarak",
        "Penerapan Interaksi Komunitas Terbatas Periode 2",
        "Gerakan Penutupan Aktivitas Penduduk",
        "Pemberlakuan Kegiatan Terbatas",
        "Interaksi Negara Berjarak Tingkat Mikro Sistematis",
        "Strategi Interaksi Resktriktif",
        "Penerapan Kegiatan Sosial Terbatas",
        "Perealisasian Restriksi Aktivitas Publik",
        "Gerakan Taat Jaga Jarak Zona Regional",
        "Pengurangan Aktivitas Zona Global",
        "Aktivitas Bangsa Berjarak Tingkat Global",
        "Himbauan Nasional Pengurangan Aktivitas Sosial Terpadu",
        "Skema Patuh Masker Tingkat Mikro",
        "Gerakan Nasional Aktivitas Penduduk Resktriktif",
        "Gerakan Nasional Bangsa Taat Prokes",
        "Aktivitas Penduduk Resktriktif Menyeluruh Sistematis",
        "Langkah Nasional Patuh Jaga Jarak Tingkat Mikro",
        "Pengetatan Kegiatan Penduduk Berskala Makro",
        "Perealisasian Patuh Jaga Jarak Menyeluruh",
        "Gerakan Nasional Supresi Kegiatan Bangsa",
        "Kegiatan Masyarakat Resktriktif Tingkat Nasional",
        "Strategi Kegiatan Sosial Berjarak 5.0",
        "Pengaplikasian Bangsa Taat Masker",
        "Pengurangan Kegiatan Bangsa Skala Besar Terpadu",
        "Interaksi Berjarak Skala Nasional",
        "Pembatasan Kegiatan Kependudukan Berskala Makro",
        "Pengurangan Interaksi Menyeluruh",
        "Pengetatan Kegiatan Warga Nasional",
        "Interaksi Warga Terbatas Zona Makro",
        "Indonesia Wajib Masker Menyeluruh",
        "Supresi Kegiatan Zona Nasional Gelombang 3",
        "Himbauan Nasional Aktivitas Resktriktif Skala Besar",
        "Langkah Nasional Restriksi Kegiatan Publik",
        "Masyarakat Patuh Prokes Nasional",
        "Aktivitas Terbatas Tingkat Regional",
        "Supresi Aktivitas Skala Besar",
        "Restriksi Interaksi Berskala Masif",
        "Penerapan Taat Prokes Skala Besar",
        "Himbauan Wajib Masker Zona Regional",
        "Kegiatan Warga Berjarak Berskala Nasional Periode Lanjutan",
        "Operasi Interaksi Resktriktif",
        "Indonesia Wajib Masker Menyeluruh 5.0",
        "Gerakan Kegiatan Sosial Terbatas",
        "Kegiatan Komunitas Berjarak Tingkat Mikro",
        "Strategi Nasional Bangsa Patuh Masker",
        "Pengaplikasian Aktivitas Resktriktif Tingkat Global",
        "Interaksi Berjarak Skala Masif 2.0",
        "Kegiatan Bangsa Resktriktif Skala Regional Terpadu",
        "Kegiatan Terbatas Tingkat Nasional Sistematis",
        "Penerapan Warga Wajib Masker",
        "Gerakan Nasional Kegiatan Berjarak Nasional",
        "Aktivitas Komunitas Berjarak Nasional",
        "Warga Patuh Jaga Jarak Nasional",
        "Langkah Nasional Interaksi Terbatas Berskala Masif",
        "Aktivitas Warga Resktriktif Zona Global 2.0",
        "Kegiatan Negara Berjarak Berskala Masif 2.0",
        "Pelaksanaan Kegiatan Antarmuka Terbatas",
        "Langkah Nasional Jaga Jarak Skala Mikro",
        "Pengaplikasian Kegiatan Berjarak Zona Makro",
        "Operasi Aktivitas Berjarak Berskala Besar",
        "Penutupan Interaksi Masyarakat Berskala Nasional",
        "Pengaplikasian Interaksi Berjarak Nasional",
        "Masyarakat Taat Prokes Zona Nasional",
        "Aktivitas Negara Resktriktif Nasional",
        "Pengurangan Kegiatan Skala Masif",
        "Himbauan Interaksi Bangsa Resktriktif Sistematis",
        "Warga Patuh Jaga Jarak Berskala Masif",
        "Gerakan Aktivitas Resktriktif Gelombang 4",
        "Gerakan Nasional Aktivitas Terbatas Terpadu",
        "Operasi Kegiatan Terbatas",
        "Strategi Kegiatan Resktriktif",
        "Interaksi Kependudukan Resktriktif Berskala Mikro Periode Lanjutan",
        "Pemberlakuan Kegiatan Kependudukan Berjarak",
        "Interaksi Penduduk Berjarak Menyeluruh Periode 5",
        "Bangsa Wajib Masker Tingkat Makro",
        "Kegiatan Berjarak Tingkat Nasional",
        "Skema Kegiatan Berjarak Terpadu",
        "Operasi Aktivitas Resktriktif",
        "Kegiatan Sosial Terbatas Skala Mikro",
        "Perealisasian Supresi Kegiatan Masyarakat",
        "Perealisasian Aktivitas Berjarak Zona Makro Terstruktur",
        "Supresi Interaksi Sosial Skala Makro",
        "Penjarakan Aktivitas Zona Mikro",
        "Pemberlakuan Patuh Prokes Zona Mikro 3.0",
        "Skema Nasional Masyarakat Taat Prokes",
        "Pelaksanaan Warga Jaga Jarak",
        "Interaksi Antarmuka Resktriktif Zona Mikro",
        "Langkah Nasional Warga Taat Masker Sistematis",
        "Kegiatan Warga Terbatas Nasional",
        "Penjarakan Aktivitas Penduduk Tingkat Mikro",
        "Restriksi Kegiatan Skala Mikro Terpadu",
        "Supresi Aktivitas Skala Mikro Terpadu",
        "Warga Taat Jaga Jarak Tingkat Global",
        "Interaksi Terbatas Tingkat Regional",
        "Perealisasian Indonesia Wajib Jaga Jarak",
        "Himbauan Interaksi Berjarak Terstruktur",
        "Pelaksanaan Penjarakan Interaksi Penduduk",
        "Perealisasian Kegiatan Resktriktif Skala Nasional",
        "Himbauan Nasional Kegiatan Resktriktif",
        "Skema Nasional Kegiatan Berjarak",
        "Perealisasian Restriksi Interaksi Negara",
        "Indonesia Taat Masker Tingkat Nasional",
        "Pemberlakuan Interaksi Berjarak",
        "Operasi Taat Jaga Jarak Nasional",
        "Strategi Pengetatan Interaksi Publik Terpadu",
        "Indonesia Jaga Jarak Menyeluruh",
        "Indonesia Taat Jaga Jarak Berskala Nasional",
        "Bangsa Jaga Jarak Zona Regional",
        "Pengaplikasian Interaksi Berjarak Berskala Masif",
        "Gerakan Nasional Jaga Jarak Tingkat Mikro",
        "Pengurangan Kegiatan Nasional",
        "Pelaksanaan Taat Jaga Jarak Skala Makro",
        "Masyarakat Wajib Jaga Jarak Tingkat Mikro",
        "Indonesia Taat Masker Zona Regional",
        "Himbauan Aktivitas Resktriktif Terstruktur",
        "Perealisasian Kegiatan Resktriktif Berskala Besar Terstruktur",
        "Penerapan Jaga Jarak Tingkat Makro Sistematis",
        "Strategi Kegiatan Berjarak Nasional",
        "Pengetatan Aktivitas Bangsa Zona Mikro",
        "Pengurangan Kegiatan Warga Skala Global",
        "Pengetatan Aktivitas Negara Menyeluruh",
        "Skema Nasional Aktivitas Kependudukan Terbatas",
        "Penerapan Patuh Prokes Menyeluruh Terpadu",
        "Strategi Nasional Interaksi Sosial Berjarak",
        "Skema Nasional Kegiatan Resktriktif Terstruktur",
        "Pembatasan Aktivitas Menyeluruh Terstruktur",
        "Pengaplikasian Taat Jaga Jarak Zona Mikro",
        "Langkah Nasional Warga Wajib Masker",
        "Gerakan Interaksi Komunitas Terbatas Terpadu",
        "Pemberlakuan Pengurangan Aktivitas Penduduk",
        "Kegiatan Kependudukan Terbatas Nasional",
        "Penjarakan Aktivitas Zona Global Sistematis",
        "Penutupan Kegiatan Berskala Makro",
        "Kegiatan Masyarakat Resktriktif Zona Regional",
        "Masyarakat Patuh Masker Tingkat Global",
        "Interaksi Terbatas Berskala Mikro",
        "Interaksi Resktriktif Zona Makro",
        "Himbauan Nasional Bangsa Wajib Masker",
        "Pembatasan Aktivitas Sosial Skala Mikro",
        "Penerapan Penjarakan Interaksi Antarmuka",
        "Pengaplikasian Kegiatan Resktriktif",
        "Pemberlakuan Interaksi Terbatas",
        "Pengaplikasian Restriksi Interaksi Sosial Periode 4",
        "Skema Kegiatan Terbatas Tingkat Mikro",
        "Perealisasian Supresi Interaksi Negara",
        "Gerakan Patuh Masker Skala Mikro",
        "Perealisasian Kegiatan Berjarak Skala Mikro",
        "Gerakan Nasional Penutupan Interaksi Kependudukan",
        "Gerakan Nasional Masyarakat Patuh Masker",
        "Langkah Nasional Interaksi Terbatas",
        "Langkah Nasional Supresi Aktivitas Masyarakat",
        "Skema Nasional Wajib Jaga Jarak Zona Nasional",
        "Kegiatan Kependudukan Terbatas Skala Global",
        "Skema Nasional Aktivitas Warga Terbatas",
        "Perealisasian Penutupan Kegiatan Sosial",
        "Strategi Warga Taat Masker",
        "Gerakan Nasional Interaksi Warga Terbatas Gelombang 4",
        "Skema Supresi Interaksi Publik",
        "Strategi Indonesia Wajib Prokes",
        "Restriksi Aktivitas Bangsa Skala Nasional",
        "Restriksi Aktivitas Menyeluruh",
        "Pengetatan Aktivitas Masyarakat Berskala Regional",
        "Pengaplikasian Interaksi Terbatas Nasional",
        "Pelaksanaan Supresi Aktivitas Publik",
        "Himbauan Nasional Taat Jaga Jarak Tingkat Nasional",
        "Bangsa Wajib Prokes Tingkat Mikro",
        "Strategi Aktivitas Negara Berjarak",
        "Operasi Masyarakat Taat Prokes",
        "Interaksi Antarmuka Berjarak Nasional",
        "Penutupan Kegiatan Tingkat Global",
        "Gerakan Nasional Aktivitas Berjarak Periode 5",
        "Indonesia Wajib Masker Berskala Regional",
        "Gerakan Aktivitas Resktriktif Berskala Makro Periode 3",
        "Himbauan Nasional Bangsa Patuh Masker Gelombang 3",
        "Operasi Masyarakat Jaga Jarak Sistematis",
        "Interaksi Negara Terbatas Menyeluruh Sistematis",
        "Interaksi Resktriktif Nasional",
        "Gerakan Masyarakat Patuh Jaga Jarak Terstruktur",
        "Pengaplikasian Interaksi Resktriktif",
        "Himbauan Nasional Interaksi Resktriktif Tingkat Regional Sistematis",
        "Penjarakan Interaksi Zona Makro",
        "Gerakan Nasional Kegiatan Resktriktif Menyeluruh",
        "Pelaksanaan Masyarakat Patuh Jaga Jarak",
        "Warga Patuh Prokes Zona Mikro",
        "Gerakan Kegiatan Warga Resktriktif",
        "Penjarakan Kegiatan Tingkat Regional",
        "Himbauan Nasional Aktivitas Terbatas Menyeluruh Terpadu",
        "Himbauan Nasional Masyarakat Jaga Jarak",
        "Interaksi Terbatas Zona Makro",
        "Penutupan Kegiatan Warga Berskala Makro",
        "Supresi Kegiatan Warga Zona Nasional Terpadu",
        "Kegiatan Berjarak Skala Regional Terpadu",
        "Strategi Nasional Pengurangan Aktivitas Bangsa",
        "Strategi Nasional Interaksi Kependudukan Resktriktif",
        "Strategi Nasional Restriksi Kegiatan Publik",
        "Interaksi Sosial Terbatas Zona Global",
        "Strategi Nasional Restriksi Aktivitas Sosial Terstruktur",
        "Pengaplikasian Bangsa Taat Masker Sistematis",
        "Penerapan Interaksi Berjarak Berskala Masif",
        "Bangsa Patuh Prokes Menyeluruh",
        "Pelaksanaan Masyarakat Taat Prokes 4.0",
        "Aktivitas Terbatas Zona Nasional Sistematis",
        "Warga Taat Prokes Skala Masif",
        "Skema Nasional Indonesia Jaga Jarak",
        "Interaksi Warga Terbatas Skala Makro",
        "Pembatasan Kegiatan Nasional",
        "Aktivitas Berjarak Nasional 3.0",
        "Pengetatan Aktivitas Warga Zona Global",
        "Supresi Interaksi Tingkat Regional",
        "Pemberlakuan Wajib Masker Tingkat Nasional",
        "Himbauan Nasional Interaksi Sosial Berjarak",
        "Bangsa Wajib Prokes Berskala Nasional",
        "Kegiatan Resktriktif Skala Masif",
        "Penerapan Interaksi Berjarak Tingkat Mikro",
        "Perealisasian Interaksi Resktriktif",
        "Skema Kegiatan Terbatas",
        "Pembatasan Aktivitas Penduduk Nasional",
        "Pengurangan Aktivitas Warga Skala Global",
        "Indonesia Wajib Prokes Nasional",
        "Pengetatan Aktivitas Negara Nasional",
        "Kegiatan Berjarak Tingkat Mikro",
        "Himbauan Penutupan Interaksi Bangsa Periode 4",
        "Operasi Interaksi Negara Terbatas",
        "Himbauan Nasional Indonesia Wajib Jaga Jarak",
        "Himbauan Nasional Kegiatan Berjarak Berskala Makro",
        "Skema Kegiatan Berjarak Terstruktur",
        "Pengetatan Interaksi Tingkat Global Sistematis",
        "Kegiatan Sosial Berjarak Berskala Regional",
        "Gerakan Nasional Wajib Jaga Jarak Berskala Nasional",
        "Pengurangan Aktivitas Komunitas Berskala Besar",
        "Masyarakat Wajib Masker Tingkat Makro",
        "Penutupan Kegiatan Berskala Global Terpadu",
        "Interaksi Negara Berjarak Nasional",
        "Gerakan Nasional Kegiatan Resktriktif Skala Makro",
        "Strategi Nasional Kegiatan Resktriktif Tingkat Mikro Terstruktur",
        "Skema Aktivitas Terbatas",
        "Interaksi Berjarak Zona Mikro",
        "Penjarakan Aktivitas Komunitas Zona Nasional",
        "Penjarakan Interaksi Publik Menyeluruh",
        "Pengaplikasian Bangsa Wajib Masker 2.0",
        "Penjarakan Aktivitas Berskala Global",
        "Aktivitas Penduduk Resktriktif Skala Nasional",
        "Gerakan Nasional Taat Masker Skala Masif",
        "Indonesia Wajib Prokes Tingkat Regional 5.0",
        "Penutupan Interaksi Publik Nasional",
        "Kegiatan Masyarakat Berjarak Skala Global",
        "Strategi Aktivitas Terbatas Menyeluruh",
        "Pemberlakuan Warga Jaga Jarak",
        "Pengetatan Kegiatan Zona Regional",
        "Skema Nasional Kegiatan Resktriktif",
        "Kegiatan Publik Terbatas Skala Makro Terstruktur",
        "Strategi Pembatasan Aktivitas Bangsa",
        "Strategi Aktivitas Berjarak",
        "Skema Penutupan Kegiatan Masyarakat",
        "Restriksi Aktivitas Skala Regional",
        "Pengurangan Interaksi Penduduk Berskala Besar Terstruktur",
        "Pengurangan Aktivitas Kependudukan Zona Global Terstruktur",
        "Pelaksanaan Wajib Prokes Berskala Besar 5.0",
        "Perealisasian Kegiatan Warga Berjarak",
        "Penjarakan Aktivitas Tingkat Global",
        "Warga Wajib Prokes Berskala Nasional",
        "Pelaksanaan Aktivitas Berjarak",
        "Masyarakat Wajib Jaga Jarak Menyeluruh",
        "Pengetatan Aktivitas Penduduk Nasional",
        "Penutupan Interaksi Berskala Mikro",
        "Himbauan Penjarakan Kegiatan Penduduk",
        "Perealisasian Penjarakan Aktivitas Sosial",
        "Operasi Aktivitas Sosial Resktriktif",
        "Indonesia Wajib Masker Skala Mikro",
        "Penerapan Kegiatan Terbatas Zona Regional",
        "Himbauan Interaksi Komunitas Berjarak",
        "Aktivitas Resktriktif Skala Makro",
        "Skema Supresi Aktivitas Publik",
        "Pengaplikasian Aktivitas Resktriktif Nasional Terstruktur",
        "Pemberlakuan Bangsa Jaga Jarak",
        "Pengaplikasian Supresi Aktivitas Masyarakat",
        "Pemberlakuan Taat Jaga Jarak Tingkat Makro",
        "Pengaplikasian Aktivitas Publik Terbatas",
        "Langkah Nasional Wajib Prokes Zona Nasional",
        "Strategi Nasional Aktivitas Antarmuka Resktriktif",
        "Himbauan Interaksi Warga Terbatas",
        "Pengetatan Kegiatan Publik Skala Global Terstruktur",
        "Penjarakan Interaksi Sosial Menyeluruh",
        "Operasi Masyarakat Taat Masker",
        "Pengurangan Interaksi Sosial Menyeluruh Terpadu",
        "Strategi Pengurangan Kegiatan Masyarakat",
        "Perealisasian Pengetatan Interaksi Warga Terstruktur",
        "Masyarakat Taat Masker Zona Mikro",
        "Warga Patuh Prokes Menyeluruh",
        "Kegiatan Penduduk Berjarak Skala Masif",
        "Skema Nasional Patuh Jaga Jarak Nasional Gelombang 5",
        "Interaksi Komunitas Berjarak Berskala Makro",
        "Pengurangan Interaksi Penduduk Skala Besar",
        "Skema Kegiatan Penduduk Berjarak",
        "Skema Interaksi Kependudukan Terbatas",
        "Interaksi Antarmuka Terbatas Menyeluruh",
        "Skema Wajib Prokes Skala Global",
        "Kegiatan Warga Resktriktif Skala Global",
        "Kegiatan Resktriktif Zona Regional",
        "Strategi Masyarakat Wajib Prokes",
        "Gerakan Supresi Kegiatan Komunitas",
        "Interaksi Komunitas Terbatas Tingkat Mikro",
        "Penjarakan Interaksi Berskala Masif",
        "Interaksi Terbatas Tingkat Makro",
        "Pembatasan Interaksi Tingkat Nasional",
        "Strategi Nasional Kegiatan Terbatas Nasional",
        "Operasi Penutupan Interaksi Penduduk",
        "Indonesia Jaga Jarak Zona Makro",
        "Interaksi Warga Terbatas Skala Besar",
        "Langkah Nasional Interaksi Berjarak Zona Regional",
        "Skema Nasional Bangsa Wajib Jaga Jarak",
        "Gerakan Nasional Penjarakan Interaksi Penduduk Sistematis",
        "Indonesia Wajib Jaga Jarak Tingkat Nasional",
        "Interaksi Negara Terbatas Berskala Regional",
        "Strategi Supresi Interaksi Kependudukan",
        "Himbauan Nasional Aktivitas Berjarak Tingkat Mikro",
        "Perealisasian Aktivitas Sosial Berjarak",
        "Operasi Kegiatan Bangsa Terbatas Terstruktur",
        "Aktivitas Terbatas Berskala Masif",
        "Aktivitas Resktriktif Berskala Global",
        "Perealisasian Aktivitas Berjarak Tingkat Nasional",
        "Pengurangan Aktivitas Kependudukan Berskala Nasional Terstruktur",
        "Bangsa Taat Prokes Tingkat Regional",
        "Pengurangan Kegiatan Sosial Nasional",
        "Aktivitas Kependudukan Resktriktif Menyeluruh Terstruktur",
        "Pemberlakuan Kegiatan Resktriktif Nasional Periode 4",
        "Indonesia Taat Jaga Jarak Nasional Terstruktur",
        "Pembatasan Kegiatan Tingkat Global",
        "Gerakan Nasional Interaksi Terbatas Menyeluruh",
        "Interaksi Berjarak Berskala Masif",
        "Gerakan Supresi Aktivitas Bangsa",
        "Pengetatan Aktivitas Berskala Regional 2.0"
    ];
    var randomNumber = Math.floor(Math.random() * textArray.length);
    quote.innerHTML = `<h3 class ="animate__animated animate__zoomInDown infinite pulse 1s">` + textArray[randomNumber] + `</h3>`;

}

getrandomquote()